Parameters:
  VPCname:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  ## VPC
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref VPCname
  ## Private Subnet
  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24

  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: zone-id
      VpcId: vpc-id
      CidrBlock: --.--.--.--/--
      Tags:
        - Key: keyname
          Value: value

  routeTableName:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: vpc-id
      Tags:
        - Key: keyname
          Value: value
